# Generated by Django 5.1.1 on 2024-09-30 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_alter_flashcard_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
